### ISSUE TITLE
Additional rights are required

### ISSUE THREAD

**Issue by Mortinke** [Netflix-Skunkworks/aardvark#12]
The following rights are mentioned in the Readme:
```
iam:GenerateServiceLastAccessedDetails
iam:GetServiceLastAccessedDetails
iam:listrolepolicies
iam:listroles
```

With the current commit, "iam:ListUsers", "iam:ListPolicies" and "iam:ListGroups" are also necessary:
```
(venv) ubuntu@*******:/usr/local/src/aardvark$ git show
commit 86021eb8c5e7ee74c8685bb2d925dfff046fd846
Author: Thomas Desrosiers <thomaso-mirodin@users.noreply.github.com>
Date:   Sun Aug 6 09:37:06 2017 -0700

    Fix syntax error in updater (#11)

    👍

diff --git a/aardvark/updater/__init__.py b/aardvark/updater/__init__.py
index 00a8675..e9d081f 100644
--- a/aardvark/updater/__init__.py
+++ b/aardvark/updater/__init__.py
@@ -3,7 +3,7 @@ import os
 import tempfile
 import urllib

-from cloudaux.aws.iam import list_roles
+from cloudaux.aws.iam import list_roles, list_users
 from cloudaux.aws.sts import boto3_cached_conn
 import requests
 import subprocess32
@@ -61,10 +61,13 @@ class AccountToUpdate(object):
         client = boto3_cached_conn(
             'iam', service_type='client', **self.conn_details)

-        account_arns = set(
-            [role['Arn'] for role in list_roles(**self.conn_details)]
-            + [user['Arn'] for user in list_users(**self.conn_details)]
-        )
+        account_arns = set()
+
+        for role in list_roles(**self.conn_details):
+            account_arns.add(role['Arn'])
+
+        for user in list_users(**self.conn_details):
+            account_arns.add(user['Arn'])

         for page in client.get_paginator('list_policies').paginate(Scope='Local'):
             for policy in page['Policies']:
```

Otherwise, I get one of the following errors:
iam:ListGroups
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/src/aardvark/aardvark/manage.py", line 48, in run
    ret_code, aa_data = account.update_account()
  File "/usr/local/src/aardvark/aardvark/updater/__init__.py", line 39, in update_account
    arns = self._get_arns()
  File "/usr/local/src/aardvark/aardvark/updater/__init__.py", line 76, in _get_arns
    for page in client.get_paginator('list_groups').paginate():
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/botocore-1.5.92-py2.7.egg/botocore/paginate.py", line 249, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/botocore-1.5.92-py2.7.egg/botocore/paginate.py", line 326, in _make_reques                     t
    return self._method(**current_kwargs)
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/botocore-1.5.92-py2.7.egg/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/botocore-1.5.92-py2.7.egg/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AccessDenied) when calling the ListGroups operation: User: arn:aws:sts::**********:assumed-role/Aardvark/                     aardvark is not authorized to perform: iam:ListGroups on resource: arn:aws:iam::**********:group/
```
iam:ListPolicies
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/src/aardvark/aardvark/manage.py", line 48, in run
    ret_code, aa_data = account.update_account()
  File "/usr/local/src/aardvark/aardvark/updater/__init__.py", line 39, in update_account
    arns = self._get_arns()
  File "/usr/local/src/aardvark/aardvark/updater/__init__.py", line 72, in _get_arns
    for page in client.get_paginator('list_policies').paginate(Scope='Local'):
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/botocore-1.5.92-py2.7.egg/botocore/paginate.py", line 249, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/botocore-1.5.92-py2.7.egg/botocore/paginate.py", line 326, in _make_reques                     t
    return self._method(**current_kwargs)
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/botocore-1.5.92-py2.7.egg/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/botocore-1.5.92-py2.7.egg/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AccessDenied) when calling the ListPolicies operation: User: arn:aws:sts::**********:assumed-role/Aardvar                     k/aardvark is not authorized to perform: iam:ListPolicies on resource: policy path /
```
iam:ListUsers:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/src/aardvark/aardvark/manage.py", line 48, in run
    ret_code, aa_data = account.update_account()
  File "/usr/local/src/aardvark/aardvark/updater/__init__.py", line 39, in update_account
    arns = self._get_arns()
  File "/usr/local/src/aardvark/aardvark/updater/__init__.py", line 69, in _get_arns
    for user in list_users(**self.conn_details):
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/cloudaux-1.3.5-py2.7.egg/cloudaux/aws/sts.py", line 129, in decorated_func                     tion
    return f(*args, **kwargs)
  File "/usr/local/src/aardvark/venv/lib/python2.7/site-packages/cloudaux-1.3.5-py2.7.egg/cloudaux/aws/decorators.py", line 40, in decorate                     d_function
    raise e
ClientError: An error occurred (AccessDenied) when calling the ListUsers operation: User: arn:aws:sts::**********:assumed-role/Aardvark/a                     ardvark is not authorized to perform: iam:ListUsers on resource: arn:aws:iam::**********:user/
```

**Comment by mcpeak** [comment]
Oh ok cool, I'll add to the README.  Thanks!

**Comment by mcpeak** [comment]
Merged fix to README, closing.
